# Generated by Django 5.2 on 2026-02-24 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("github_link", models.URLField(blank=True, null=True)),
                ("kaggle_link", models.URLField(blank=True, null=True)),
                ("live_link", models.URLField(blank=True, null=True)),
                (
                    "time_spent",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2 weeks', '3 months'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '150 MB', '2.5 GB'",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/media/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/videos/"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
